### ISSUE TITLE
Redmine trunk (r16887, Rails 5.1) で rake redmine:plugins:migrate が実行できない

### ISSUE THREAD

**Issue by vividtone** [agileware-jp/redmine_work_days#16]
migrationを実行しようとしたところ以下のエラーが発生しました。

```
$ bundle exec rake redmine:plugins:migrate NAME=redmine_work_days
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param
/Users/maeda/redmines/redmine-trunk/plugins/redmine_work_days/init.rb:6:in `<top (required)>'
/Users/maeda/redmines/gems/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
.
.
.
```

**Comment by springkuma** [comment]
to_prepareコールバックは、`ActiveSupport::Reloader`に移ったみたいですね。たぶんほとんどのプラグインで修正が必要かと。
(該当のコードの修正でいうと `ActiveSupport::Callbacks.to_prepare` に書き換える、ではダメかもしれません。本体のコード読む限りでは4系でdelegateしてたのがしなくなっているように見えた。`ActiveSupport::Reloader.to_prepare`かな？ちょっとやってみないとわからないですが。)
あと、4系以前と5系の両対応する必要がありますね。
